scrapping_task:
  description: >
    Conduct a thorough research online about the list of companies relevant to {company_name}.
    Make sure you find all the {topic} for the past 3 years.
  expected_output: >
    A list of links to PDF for the {topic} of each company that're saved locally.
  agent: scrapper

researching_task:
  description: >
    Read through all the {topic} saved, and extract 5 key financial metrics (KPI) to calculate the CAGR. Provide reasoning on why the KPI is selected.
  expected_output: >
    A table with key financial metrics from each companies.
    A short summary of the findings.
  agent: researcher

building_task:
  description: >
    Put the key financial metrics into a concise table, and plot a graph to visualize the trends.
    Make sure to include the summary from researching_task as a footnote.
  expected_output: >
    A table and a graph showing the key financial metrics.
    Followed by a short summary of the trends and insights.
  agent: builder